### PR TITLE
Add health & safety protocols

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@sallyom @langdon PTAL

**Comment by sallyom** [comment]
/lgtm 
Thanks @umohnani8

**Comment by umohnani8** [comment]
@jridky this is ready to be merged.

**Comment by langdon** [comment]
I skimmed the code (rather than ran it) but lgtm

**Pull request merged**
