### PR TITLE
Update topics for DevConf.US

### PR DESCRIPTION
**Pull request by umohnani8**
Added some new topics and descriptins for all the
topics listed here.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@jridky PTAL

**Comment by jridky** [comment]
LGTM

**Comment by jridky** [comment]
I suppose, those topics can be set in CfP portal as well? @umohnani8

**Comment by umohnani8** [comment]
@jridky yes please!

**Pull request merged**
