### PR TITLE
adding in a little js to redirect based on host header

### PR DESCRIPTION
**Pull request by langdon**
should work on the existing setup too

### CODE REVIEW

**Comment by jridky** [comment]
This will not work with current domain setup.
When someone write www.devconf.cz in web browser, firebase will automatically redirect him/her to devconf.info. As result, your change will be always proceeded under devconf.info domain.
Now, we are using cloudflare DNS and HTTP proxy. As result of HTTP proxy, all *devconf.cz/* HTTP requests are rewritten to devconf.info/cz/

**Comment by bexelbie** [comment]
If merging this won't hurt our existing .cz setup, I suggest we do it so we can use this for other non-cloudflare hosted sites in the interim.

**Comment by jridky** [comment]
Merging of this will not hurt anything, but even when we omit cloudflare setup and stay with firebase hosting setup only, it will not take any effect. For website it will be dead code, due redirection from .cz|.in|.live domain is done prior this code is proceed. 

For .us domain there is a different situation, due redirection from that domain is solved in different way, than for .cz|.in|.live, but result is the same. Redirection is done prior this code is proceed.

**Comment by nigelbabu** [comment]
Right, can we talk about this pull request now?

We currently redirect devconf.in -> devconf.info at the Firebase control panel. If we turn it off, the website will be served off devconf.in and then this pull request will take effect.

**Comment by jridky** [comment]
Yes, you're right. If we disable redirection in Firebase administration, than this code should work.

**Pull request merged**
